<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    public function run(): void
    {
        $banks = [
            1 => 'AB Bank PLC',
            2 => 'Airtel Payments Bank Limited',
            3 => 'American Express Banking Corporation',
            4 => 'Andhra Pradesh Grameena Vikas Bank',
            5 => 'Andhra Pragathi Grameena Bank',
            6 => 'Arunachal Pradesh Rural Bank',
            7 => 'Aryavart Bank',
            8 => 'Assam Gramin Vikash Bank',
            9 => 'Au Small Finance Bank Limited',
            10 => 'Australia and New Zealand Banking Group Ltd.',
            11 => 'Axis Bank Ltd.',
            12 => 'Bandhan Bank Ltd.',
            13 => 'Bangiya Gramin Vikas Bank',
            14 => 'Bank of America',
            15 => 'Bank of Bahrain & Kuwait BSC',
            16 => 'Bank of Baroda',
            17 => 'Bank of Ceylon',
            18 => 'Bank of China',
            19 => 'Bank of India',
            20 => 'Bank of Maharashtra',
            21 => 'Bank of Nova Scotia',
            22 => 'Barclays Bank Plc.',
            23 => 'Baroda Gujarat Gramin Bank',
            24 => 'Baroda Rajasthan Kshetriya Gramin Bank',
            25 => 'Baroda UP Bank',
            26 => 'BNP Paribas',
            27 => 'Canara Bank',
            28 => 'Capital Small Finance Bank Limited',
            29 => 'Central Bank of India',
            30 => 'Chaitanya Godavari Grameena Bank',
            31 => 'Chhattisgarh Rajya Gramin Bank',
            32 => 'Citibank N.A.',
            33 => 'City Union Bank Ltd.',
            34 => 'Cooperatieve Rabobank U.A.',
            35 => 'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALY',
            36 => 'Credit Suisse A.G',
            37 => 'CSB Bank Ltd.',
            38 => 'CTBC Bank Co., Ltd.',
            39 => 'Dakshin Bihar Gramin Bank',
            40 => 'DBS Bank India Limited*',
            41 => 'DCB BANK LIMITED',
            42 => 'Deutsche Bank',
            43 => 'DHANALAKSHMI BANK',
            44 => 'Doha Bank Q.P.S.C',
            45 => 'Ellaquai Dehati Bank',
            46 => 'Emirates Bank NBD',
            47 => 'Equitas Small Finance Bank Limited',
            48 => 'ESAF Small Finance Bank Limited',
            49 => 'Federal Bank Ltd.',
            50 => 'Fino Payments Bank Limited',
            51 => 'First Abu Dhabi Bank PJSC',
            52 => 'FIRSTRAND BANK LIMITED',
            53 => 'HDFC BANK',
            54 => 'Himachal Pradesh Gramin Bank',
            55 => 'HSBC BANK',
            56 => 'ICICI Bank Ltd',
            57 => 'IDBI Bank Ltd.',
            58 => 'IDFC First Bank Ltd.',
            59 => 'India Post Payments Bank Limited',
            60 => 'Indian Bank',
            61 => 'Indian Overseas Bank',
            62 => 'INDUSIND BANK',
            63 => 'Industrial & Commercial Bank of China Ltd.',
            64 => 'Industrial Bank of Korea',
            65 => 'J.P. Morgan Chase Bank N.A.',
            66 => 'J&K Grameen Bank',
            67 => 'Jammu & Kashmir Bank Ltd.',
            68 => 'Jana Small Finance Bank Limited',
            69 => 'Jharkhand Rajya Gramin Bank',
            70 => 'JSC VTB Bank',
            71 => 'KARNATAKA BANK LIMITED',
            72 => 'Karnataka Gramin Bank',
            73 => 'Karnataka Vikas Grameena Bank',
            74 => 'Karur Vysya Bank Ltd.',
            75 => 'KEB Hana Bank',
            76 => 'Kerala Gramin Bank',
            77 => 'Kookmin Bank',
            78 => 'KOTAK MAHINDRA BANK LIMITED',
            79 => 'Krung Thai Bank Public Co. Ltd.',
            80 => 'Madhya Pradesh Gramin Bank',
            81 => 'Madhyanchal Gramin Bank',
            82 => 'Maharashtra Gramin Bank',
            83 => 'Manipur Rural Bank',
            84 => 'Mashreq Bank PSC',
            85 => 'Meghalaya Rural Bank',
            86 => 'Mizoram Rural Bank',
            87 => 'MIZUHO CORPORATE BANK LIMITED',
            88 => 'MUFG Bank, Ltd.',
            89 => 'Nagaland Rural Bank',
            90 => 'Nainital Bank Ltd.',
            91 => 'NatWest Markets Plc',
            92 => 'NongHyup Bank',
            93 => 'North East Small Finance Bank Limited',
            94 => 'Odisha Gramya Bank',
            95 => 'Paschim Banga Gramin Bank',
            96 => 'Paytm Payments Bank Limited',
            97 => 'Prathama UP Gramin Bank',
            98 => 'PT Bank Maybank Indonesia TBK',
            99 => 'Puduvai Bharathiar Grama Bank',
            100 => 'Punjab & Sind Bank',
            101 => 'Punjab Gramin Bank',
            102 => 'Punjab National Bank',
            103 => 'Qatar National Bank (Q.P.S.C.)',
            104 => 'Rajasthan Marudhara Gramin Bank',
            105 => 'RBL Bank Ltd.',
            106 => 'Saptagiri Grameena Bank',
            107 => 'Sarva Haryana Gramin Bank',
            108 => 'Saurashtra Gramin Bank',
            109 => 'Sberbank',
            110 => 'SBM Bank (India) Limited*',
            111 => 'Shinhan Bank',
            112 => 'Shivalik Small Finance Bank Limited',
            113 => 'Societe Generale',
            114 => 'Sonali Bank PLC',
            115 => 'South Indian Bank Ltd.',
            116 => 'Standard Chartered Bank',
            117 => 'State Bank of India',
            118 => 'Sumitomo Mitsui Banking Corporation',
            119 => 'Suryoday Small Finance Bank Limited',
            120 => 'Tamil Nadu Grama Bank',
            121 => 'Tamilnad Mercantile Bank Ltd.',
            122 => 'Telangana Grameena Bank',
            123 => 'Tripura Gramin Bank',
            124 => 'UCO Bank',
            125 => 'Ujjivan Small Finance Bank Limited',
            126 => 'Union Bank of India',
            127 => 'United Overseas Bank Ltd',
            128 => 'Unity Small Finance Bank Limited',
            129 => 'Utkal Grameen bank',
            130 => 'Utkarsh Small Finance Bank Limited',
            131 => 'Uttar Bihar Gramin Bank',
            132 => 'Uttarakhand Gramin Bank',
            133 => 'Uttarbanga Kshetriya Gramin Bank',
            134 => 'Vidharbha Konkan Gramin Bank',
            135 => 'Woori Bank',
            136 => 'YES Bank Ltd.',
            168 => 'ABU DHABI COMMERCIAL BANK',
            169 => 'ABHYUDAYA COOPERATIVE BANK LIMITED',
            170 => 'ALLAHABAD BANK',
            171 => 'ANDHRA BANK',
            179 => 'BANK OF TOKYO MITSUBISHI LIMITED',
            181 => 'BASSEIN CATHOLIC COOPERATIVE BANK LIMITED',
            182 => 'B N P PARIBAS',
            184 => 'CATHOLIC SYRIAN BANK LIMITED',
            186 => 'CHINATRUST COMMERCIAL BANK LIMITED',
            188 => 'CITIZEN CREDIT COOPERATIVE BANK LIMITED',
            190 => 'CORPORATION BANK',
            192 => 'DEVELOPMENT BANK OF SINGAPORE',
            193 => 'DENA BANK',
            198 => 'DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION',
            199 => 'DOMBIVLI NAGARI SAHAKARI BANK LIMITED',
            208 => 'ING VYSYA BANK',
            209 => 'JANAKALYAN SAHAKARI BANK LIMITED',
            210 => 'JANASEVA SAHAKARI BANK LIMITED',
            211 => 'KAPOL COOPERATIVE BANK LIMITED',
            215 => 'MAHANAGAR COOPERATIVE BANK',
            216 => 'MAHARASHTRA STATE COOPERATIVE BANK',
            217 => 'MASHREQBANK PSC',
            218 => 'THE DISTRICT CO-OPERATIVE CENTRAL BANK LTD',
            219 => 'Shamrao Vithal Co-operative Bank',
            220 => 'Pragathi gramin bank',
            221 => 'SYNDICATE ',
            223 => 'KARNATAKA STATE COOPERATIVE APEX BANK LIMITED',
        ];

        foreach ($banks as $id => $name) {
            DB::table('mas_bank')->updateOrInsert(
                ['id' => $id],
                [
                    'mas_bank_name'      => $name,
                    'mas_bank_status_id' => 1,
                    'created_at'         => now(),
                    'updated_at'         => now(),
                ]
            );
        }
    }
}
