<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Afghan',
            'Albanian',
            'Algerian',
            'American',
            'Andorran',
            'Angolan',
            'Argentine',
            'Armenian',
            'Australian',
            'Austrian',
            'Azerbaijani',
            'Bahraini',
            'Bangladeshi',
            'Belarusian',
            'Belgian',
            'Belizean',
            'Beninese',
            'Bhutanese',
            'Bolivian',
            'Bosnian',
            'Botswanan',
            'Brazilian',
            'British',
            'Bruneian',
            'Bulgarian',
            'Burkinabe',
            'Burmese',
            'Burundian',
            'Cambodian',
            'Cameroonian',
            'Canadian',
            'Chadian',
            'Chilean',
            'Chinese',
            'Colombian',
            'Congolese',
            'Costa Rican',
            'Croatian',
            'Cuban',
            'Cypriot',
            'Czech',
            'Danish',
            'Djiboutian',
            'Dominican',
            'Dutch',
            'Ecuadorean',
            'Egyptian',
            'Emirati',
            'English',
            'Eritrean',
            'Estonian',
            'Ethiopian',
            'Fijian',
            'Filipino',
            'Finnish',
            'French',
            'Gabonese',
            'Gambian',
            'Georgian',
            'German',
            'Ghanaian',
            'Greek',
            'Guatemalan',
            'Guinean',
            'Guyanese',
            'Haitian',
            'Honduran',
            'Hungarian',
            'Icelandic',
            'Indian',
            'Indonesian',
            'Iranian',
            'Iraqi',
            'Irish',
            'Israeli',
            'Italian',
            'Ivorian',
            'Jamaican',
            'Japanese',
            'Jordanian',
            'Kazakh',
            'Kenyan',
            'Korean',
            'Kuwaiti',
            'Kyrgyz',
            'Laotian',
            'Latvian',
            'Lebanese',
            'Liberian',
            'Libyan',
            'Lithuanian',
            'Luxembourger',
            'Macedonian',
            'Malagasy',
            'Malawian',
            'Malaysian',
            'Maldivian',
            'Malian',
            'Maltese',
            'Mauritanian',
            'Mauritian',
            'Mexican',
            'Moldovan',
            'Mongolian',
            'Moroccan',
            'Mozambican',
            'Namibian',
            'Nepalese',
            'New Zealander',
            'Nicaraguan',
            'Nigerian',
            'Norwegian',
            'Omani',
            'Pakistani',
            'Panamanian',
            'Paraguayan',
            'Peruvian',
            'Polish',
            'Portuguese',
            'Qatari',
            'Romanian',
            'Russian',
            'Rwandan',
            'Saudi',
            'Scottish',
            'Senegalese',
            'Serbian',
            'Singaporean',
            'Slovak',
            'Slovenian',
            'Somali',
            'South African',
            'Spanish',
            'Sri Lankan',
            'Sudanese',
            'Swedish',
            'Swiss',
            'Syrian',
            'Taiwanese',
            'Tajik',
            'Tanzanian',
            'Thai',
            'Togolese',
            'Tunisian',
            'Turkish',
            'Turkmen',
            'Ugandan',
            'Ukrainian',
            'Uruguayan',
            'Uzbek',
            'Venezuelan',
            'Vietnamese',
            'Welsh',
            'Yemeni',
            'Zambian',
            'Zimbabwean',
        ];

        foreach ($data as $name) {
            DB::table('mas_nationality')->updateOrInsert(
                ['mas_nationality_name' => $name],
                [
                    'mas_nationality_status_id' => 1,
                    'created_by' => null,
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
